### ISSUE TITLE
Can't create pull request. I get "There isn’t anything to compare."

### ISSUE THREAD

**Issue by JinaDawood** [DIT112-V21/group-16#24]
I tried uploading the android app by pushing to the branch upload_app but I can't compare it with master and therefore not being able to do a pull request. I've tried several git commands i've seen on stackoverflow but nothing have worked

**Comment by platisd** [comment]
I don't see any upload_app branch therefore cannot help much until there's such a branch

**Comment by JinaDawood** [comment]
![image](https://user-images.githubusercontent.com/72136631/115082956-00169700-9f07-11eb-83ba-1b1140a30b85.png)

thats weird, it's there when I go into branches

**Comment by platisd** [comment]
You cannot merge the branches because they have nothing in common.
If I had to guess, you created a new repo in a directory that contained your Android app and then pushed it to the upload_app branch. 

Please understand that git is not used to "Upload" things to github that is "something like Dropbox" or Google drive. You should think of git as something that syncs what you have on your computer with other computers.

What you should do instead is place the directory with your app in your repository, stage, commit and push to a new branch.
